project_id = "crplzfgtfgrijpbsqbnn"

[functions.parse-resume]
verify_jwt = true

[functions.match-jobs]
verify_jwt = true

[functions.search-candidates]
verify_jwt = true

[functions.notify-employer]
verify_jwt = true

[functions.notify-message]
verify_jwt = true
