import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Loader2, GraduationCap, MessageSquare, Building, ThumbsUp, ThumbsDown, HelpCircle, Zap, DollarSign } from "lucide-react";
import { toast } from "sonner";

interface InterviewPrepProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  job: {
    title: string;
    company: string;
    description: string;
    skills_required: string[];
    requirements?: string[];
  };
  resume: {
    skills: string[];
    experience_years?: number;
  } | null;
}

interface PrepData {
  technical_questions: { question: string; tip: string; difficulty: string }[];
  behavioral_questions: { question: string; tip: string; example_framework: string }[];
  company_research_tips: string[];
  dos_and_donts: { dos: string[]; donts: string[] };
  salary_negotiation_tips: string;
  closing_questions: string[];
}

export function InterviewPrep({ open, onOpenChange, job, resume }: InterviewPrepProps) {
  const [prep, setPrep] = useState<PrepData | null>(null);
  const [loading, setLoading] = useState(false);

  const generatePrep = async () => {
    setLoading(true);
    setPrep(null);

    try {
      const { data, error } = await supabase.functions.invoke("interview-prep", {
        body: {
          jobTitle: job.title,
          jobDescription: job.description,
          jobSkills: job.skills_required,
          jobRequirements: job.requirements,
          company: job.company,
          candidateSkills: resume?.skills,
          candidateExperience: resume?.experience_years,
        },
      });

      if (error) throw error;

      if (data?.error) {
        toast.error(data.error);
        return;
      }

      setPrep(data.prep);
    } catch (err: any) {
      console.error("Interview prep error:", err);
      toast.error("Failed to generate prep. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const getDifficultyColor = (diff: string) => {
    switch (diff) {
      case "easy": return "bg-[hsl(var(--status-accepted))]/10 text-[hsl(var(--status-accepted))]";
      case "hard": return "bg-destructive/10 text-destructive";
      default: return "bg-[hsl(var(--status-pending))]/10 text-[hsl(var(--status-pending))]";
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GraduationCap className="h-5 w-5 text-primary" />
            Interview Prep
          </DialogTitle>
          <DialogDescription>
            AI-generated interview preparation for <span className="font-medium text-foreground">{job.title}</span> at {job.company}
          </DialogDescription>
        </DialogHeader>

        {!prep && !loading && (
          <div className="flex flex-col items-center gap-4 py-8">
            <div className="p-4 rounded-2xl gradient-bg shadow-glow">
              <GraduationCap className="h-10 w-10 text-primary-foreground" />
            </div>
            <p className="text-center text-muted-foreground max-w-sm">
              Get tailored interview questions, tips, and preparation material generated by AI based on the job requirements.
            </p>
            <Button onClick={generatePrep} className="gap-2">
              <Zap className="h-4 w-4" />
              Generate Interview Prep
            </Button>
          </div>
        )}

        {loading && (
          <div className="flex flex-col items-center gap-3 py-12">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-muted-foreground">Generating interview prep...</p>
          </div>
        )}

        {prep && (
          <div className="space-y-4 animate-fade-in">
            <Accordion type="multiple" defaultValue={["technical", "behavioral"]} className="space-y-2">
              {/* Technical Questions */}
              {prep.technical_questions?.length > 0 && (
                <AccordionItem value="technical" className="border rounded-lg px-4">
                  <AccordionTrigger className="hover:no-underline">
                    <span className="flex items-center gap-2 text-sm font-semibold">
                      <MessageSquare className="h-4 w-4 text-primary" />
                      Technical Questions ({prep.technical_questions.length})
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="space-y-3 pb-4">
                    {prep.technical_questions.map((q, i) => (
                      <div key={i} className="p-3 rounded-lg border bg-card">
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <p className="text-sm font-medium">{q.question}</p>
                          <Badge variant="outline" className={`text-xs shrink-0 ${getDifficultyColor(q.difficulty)}`}>
                            {q.difficulty}
                          </Badge>
                        </div>
                        <p className="text-xs text-muted-foreground flex items-start gap-1.5">
                          <Zap className="h-3 w-3 mt-0.5 shrink-0 text-primary" />
                          {q.tip}
                        </p>
                      </div>
                    ))}
                  </AccordionContent>
                </AccordionItem>
              )}

              {/* Behavioral Questions */}
              {prep.behavioral_questions?.length > 0 && (
                <AccordionItem value="behavioral" className="border rounded-lg px-4">
                  <AccordionTrigger className="hover:no-underline">
                    <span className="flex items-center gap-2 text-sm font-semibold">
                      <HelpCircle className="h-4 w-4 text-accent" />
                      Behavioral Questions ({prep.behavioral_questions.length})
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="space-y-3 pb-4">
                    {prep.behavioral_questions.map((q, i) => (
                      <div key={i} className="p-3 rounded-lg border bg-card">
                        <p className="text-sm font-medium mb-2">{q.question}</p>
                        <p className="text-xs text-muted-foreground mb-1">
                          <span className="font-medium">Tip:</span> {q.tip}
                        </p>
                        <Badge variant="outline" className="text-xs mt-1">
                          Framework: {q.example_framework}
                        </Badge>
                      </div>
                    ))}
                  </AccordionContent>
                </AccordionItem>
              )}

              {/* Company Research */}
              {prep.company_research_tips?.length > 0 && (
                <AccordionItem value="company" className="border rounded-lg px-4">
                  <AccordionTrigger className="hover:no-underline">
                    <span className="flex items-center gap-2 text-sm font-semibold">
                      <Building className="h-4 w-4 text-muted-foreground" />
                      Company Research Tips
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="pb-4">
                    <ul className="space-y-2">
                      {prep.company_research_tips.map((tip, i) => (
                        <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                          <span className="mt-1 h-1.5 w-1.5 rounded-full bg-primary shrink-0" />
                          {tip}
                        </li>
                      ))}
                    </ul>
                  </AccordionContent>
                </AccordionItem>
              )}

              {/* Do's and Don'ts */}
              {prep.dos_and_donts && (
                <AccordionItem value="dosdonts" className="border rounded-lg px-4">
                  <AccordionTrigger className="hover:no-underline">
                    <span className="flex items-center gap-2 text-sm font-semibold">
                      <ThumbsUp className="h-4 w-4 text-[hsl(var(--status-accepted))]" />
                      Do's & Don'ts
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="pb-4">
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <p className="text-xs font-semibold text-[hsl(var(--status-accepted))] flex items-center gap-1">
                          <ThumbsUp className="h-3 w-3" /> DO
                        </p>
                        {prep.dos_and_donts.dos?.map((d, i) => (
                          <p key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                            <span className="text-[hsl(var(--status-accepted))]">✓</span> {d}
                          </p>
                        ))}
                      </div>
                      <div className="space-y-2">
                        <p className="text-xs font-semibold text-destructive flex items-center gap-1">
                          <ThumbsDown className="h-3 w-3" /> DON'T
                        </p>
                        {prep.dos_and_donts.donts?.map((d, i) => (
                          <p key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                            <span className="text-destructive">✗</span> {d}
                          </p>
                        ))}
                      </div>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              )}

              {/* Salary Negotiation */}
              {prep.salary_negotiation_tips && (
                <AccordionItem value="salary" className="border rounded-lg px-4">
                  <AccordionTrigger className="hover:no-underline">
                    <span className="flex items-center gap-2 text-sm font-semibold">
                      <DollarSign className="h-4 w-4 text-[hsl(var(--status-pending))]" />
                      Salary Negotiation
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="pb-4">
                    <p className="text-sm text-muted-foreground leading-relaxed">{prep.salary_negotiation_tips}</p>
                  </AccordionContent>
                </AccordionItem>
              )}

              {/* Closing Questions */}
              {prep.closing_questions?.length > 0 && (
                <AccordionItem value="closing" className="border rounded-lg px-4">
                  <AccordionTrigger className="hover:no-underline">
                    <span className="flex items-center gap-2 text-sm font-semibold">
                      <HelpCircle className="h-4 w-4 text-primary" />
                      Questions to Ask Them
                    </span>
                  </AccordionTrigger>
                  <AccordionContent className="pb-4">
                    <ul className="space-y-2">
                      {prep.closing_questions.map((q, i) => (
                        <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                          <span className="font-medium text-foreground">{i + 1}.</span> {q}
                        </li>
                      ))}
                    </ul>
                  </AccordionContent>
                </AccordionItem>
              )}
            </Accordion>

            <Button onClick={generatePrep} variant="outline" className="w-full gap-2">
              <GraduationCap className="h-4 w-4" />
              Regenerate Prep
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
